Add Zsh check, convert hgrep alias, improve rgno

diff --git a/bin/rc-zsh-specific-settings-shell-leuven-new b/bin/rc-zsh-specific-settings-shell-leuven-new
--- a/bin/rc-zsh-specific-settings-shell-leuven-new
+++ b/bin/rc-zsh-specific-settings-shell-leuven-new
@@ -1,6 +1,12 @@
 #!/usr/bin/env zsh
 
-# Last modified: <20250704.1118>
+# Last modified: <20250801.1002>
+
+# Exit if not running in Zsh.
+if [ -z "$ZSH_VERSION" ]; then
+    printf >&2 "ERROR: This script requires Zsh. Aborting.\n"
+    exit 1
+fi
 
 # Set the maximum directory stack size to 10.
 DIRSTACKSIZE=10
